weblate/accounts/urls.py
# -*- coding: utf-8 -*-
#
# Copyright © 2012 - 2019 Michal Čihař <michal@cihar.com>
#
# This file is part of Weblate <https://weblate.org/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

from django.conf import settings
from django.conf.urls import url, include

import social_django.views

import weblate.accounts.views

# Follows copy of social_django.urls with few changes:
# - authentication requires POST (issue submitted upstream)
# - authentication stores current user (to avoid CSRF on complete)
# - removed some configurability (just to avoid additional deps)
# - the association_id has to be numeric (patch accepted upstream)
social_urls = [
    # authentication / association
    url(
        r'^login/(?P<backend>[^/]+)/$',
        weblate.accounts.views.social_auth,
        name='begin'
    ),
    url(
        r'^complete/(?P<backend>[^/]+)/$',
        weblate.accounts.views.social_complete,
        name='complete'
    ),
    # disconnection
    url(
        r'^disconnect/(?P<backend>[^/]+)/$',
        social_django.views.disconnect,
        name='disconnect'
    ),
    url(
        r'^disconnect/(?P<backend>[^/]+)/(?P<association_id>\d+)/$',
        social_django.views.disconnect,
        name='disconnect_individual'
    ),
]


urlpatterns = [
    url(
        r'^email-sent/$',
        weblate.accounts.views.EmailSentView.as_view(),
        name='email-sent'
    ),
    url(r'^password/', weblate.accounts.views.password, name='password'),
    url(
        r'^reset-api-key/',
        weblate.accounts.views.reset_api_key,
        name='reset-api-key'
    ),
    url(
        r'^reset/', weblate.accounts.views.reset_password,
        name='password_reset'
    ),
    url(
        r'^logout/',
        weblate.accounts.views.WeblateLogoutView.as_view(),
        name='logout'
    ),
    url(r'^profile/', weblate.accounts.views.user_profile, name='profile'),
    url(
        r'^watch/(?P<project>[^/]+)/',
        weblate.accounts.views.watch,
        name='watch'
    ),
    url(
        r'^unwatch/(?P<project>[^/]+)/',
        weblate.accounts.views.unwatch,
        name='unwatch'
    ),
    url(r'^remove/', weblate.accounts.views.user_remove, name='remove'),
    url(r'^confirm/', weblate.accounts.views.confirm, name='confirm'),
    url(
        r'^login/$',
        weblate.accounts.views.WeblateLoginView.as_view(),
        name='login'
    ),
    url(r'^register/$', weblate.accounts.views.register, name='register'),
    url(r'^email/$', weblate.accounts.views.email_login, name='email_login'),
    url(r'', include((social_urls, 'social_auth'), namespace='social')),
]

if 'simple_sso.sso_server' in settings.INSTALLED_APPS:
    # pylint: disable=wrong-import-position
    from simple_sso.sso_server.server import Server
    server = Server()
    urlpatterns.append(url(r'^sso/', include(server.get_urls())))

weblate/api/urls.py
# -*- coding: utf-8 -*-
#
# Copyright © 2012 - 2019 Michal Čihař <michal@cihar.com>
#
# This file is part of Weblate <https://weblate.org/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

from __future__ import unicode_literals

from django.conf.urls import url, include

from weblate.api.views import (
    ProjectViewSet, ComponentViewSet, TranslationViewSet, LanguageViewSet,
    UnitViewSet, ChangeViewSet, SourceViewSet, ScreenshotViewSet,
    Metrics
)
from weblate.api.routers import WeblateRouter

# Routers provide an easy way of automatically determining the URL conf.
router = WeblateRouter()
router.register(
    r'projects',
    ProjectViewSet
)
router.register(
    r'components',
    ComponentViewSet,
    'component',
)
router.register(
    r'translations',
    TranslationViewSet
)
router.register(
    r'languages',
    LanguageViewSet
)
router.register(
    r'changes',
    ChangeViewSet
)
router.register(
    r'units',
    UnitViewSet
)
router.register(
    r'sources',
    SourceViewSet
)
router.register(
    r'screenshots',
    ScreenshotViewSet
)


# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    url(
        r'^metrics/$',
        Metrics.as_view(),
        name='metrics',
    ),
    url(
        r'^',
        include(router.urls)
    ),
]

weblate/legal/urls.py
# -*- coding: utf-8 -*-
#
# Copyright © 2012 - 2019 Michal Čihař <michal@cihar.com>
#
# This file is part of Weblate <https://weblate.org/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

from django.conf.urls import url

from weblate.legal.views import (
    LegalView, TermsView, CookiesView, SecurityView, PrivacyView,
    tos_confirm,
)

urlpatterns = [
    url(
        r'^$',
        LegalView.as_view(),
        name='index',
    ),
    url(
        r'^terms/$',
        TermsView.as_view(),
        name='terms',
    ),
    url(
        r'^cookies/$',
        CookiesView.as_view(),
        name='cookies',
    ),
    url(
        r'^security/$',
        SecurityView.as_view(),
        name='security',
    ),
    url(
        r'^privacy/$',
        PrivacyView.as_view(),
        name='privacy',
    ),
    url(
        r'^confirm/$',
        tos_confirm,
        name='confirm',
    ),
]

weblate/urls.py
# -*- coding: utf-8 -*-
#
# Copyright © 2012 - 2019 Michal Čihař <michal@cihar.com>
#
# This file is part of Weblate <https://weblate.org/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

import re

from django.conf.urls import include, url
from django.conf import settings
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_cookie
from django.views.generic import RedirectView
import django.contrib.sitemaps.views
import django.views.i18n
import django.views.static

from weblate.trans.feeds import (
    TranslationChangesFeed, ComponentChangesFeed,
    ProjectChangesFeed, ChangesFeed, LanguageChangesFeed
)
from weblate.trans.views.changes import ChangesView, ChangesCSVView
import weblate.accounts.views
import weblate.addons.views
from weblate.auth.decorators import management_access
import weblate.checks.views
import weblate.lang.views
import weblate.memory.views
import weblate.screenshots.views
import weblate.trans.views.about
import weblate.trans.views.acl
import weblate.trans.views.agreement
import weblate.trans.views.api
import weblate.trans.views.basic
import weblate.trans.views.charts
import weblate.trans.views.create
import weblate.trans.views.dashboard
import weblate.trans.views.dictionary
import weblate.trans.views.edit
import weblate.trans.views.files
import weblate.trans.views.git
import weblate.trans.views.js
import weblate.trans.views.lock
import weblate.trans.views.manage
import weblate.trans.views.reports
import weblate.trans.views.search
import weblate.trans.views.settings
import weblate.trans.views.source
import weblate.trans.views.widgets
from weblate.sitemaps import SITEMAPS
import weblate.accounts.urls
import weblate.api.urls
import weblate.wladmin.sites

# URL regexp for language code
LANGUAGE = r'(?P<lang>[^/]+)'

# URL regexp for project
PROJECT = r'(?P<project>[^/]+)/'

# URL regexp for component
COMPONENT = PROJECT + r'(?P<component>[^/]+)/'

# URL regexp for translations
TRANSLATION = COMPONENT + LANGUAGE + '/'

# URL regexp for project language pages
PROJECT_LANG = PROJECT + LANGUAGE + '/'

# URL regexp used as base for widgets
WIDGET = r'(?P<widget>[^/-]+)-(?P<color>[^/-]+)'

# Widget extension match
EXTENSION = r'(?P<extension>(png|svg|bin))'

handler403 = weblate.trans.views.basic.denied

handler404 = weblate.trans.views.basic.not_found

handler500 = weblate.trans.views.basic.server_error

real_patterns = [
    url(
        r'^$',
        weblate.trans.views.dashboard.home,
        name='home',
    ),
    url(
        r'^projects/$',
        weblate.trans.views.basic.list_projects,
        name='projects',
    ),
    url(
        r'^projects/' + PROJECT + '$',
        weblate.trans.views.basic.show_project,
        name='project',
    ),

    # Engagement pages
    url(
        r'^engage/' + PROJECT + '$',
        weblate.trans.views.basic.show_engage,
        name='engage',
    ),
    url(
        r'^engage/' + PROJECT_LANG + '$',
        weblate.trans.views.basic.show_engage,
        name='engage',
    ),

    # Glossary/Dictionary pages
    url(
        r'^dictionaries/' + PROJECT + '$',
        weblate.trans.views.dictionary.show_dictionaries,
        name='show_dictionaries',
    ),
    url(
        r'^dictionaries/' + PROJECT_LANG + '$',
        weblate.trans.views.dictionary.show_dictionary,
        name='show_dictionary',
    ),
    url(
        r'^upload-dictionaries/' + PROJECT_LANG + '$',
        weblate.trans.views.dictionary.upload_dictionary,
        name='upload_dictionary',
    ),
    url(
        r'^delete-dictionaries/' + PROJECT_LANG + '(?P<pk>[0-9]+)/$',
        weblate.trans.views.dictionary.delete_dictionary,
        name='delete_dictionary',
    ),
    url(
        r'^edit-dictionaries/' + PROJECT_LANG + '(?P<pk>[0-9]+)/$',
        weblate.trans.views.dictionary.edit_dictionary,
        name='edit_dictionary',
    ),
    url(
        r'^download-dictionaries/' + PROJECT_LANG + '$',
        weblate.trans.views.dictionary.download_dictionary,
        name='download_dictionary',
    ),

    # Subroject pages
    url(
        r'^projects/' + COMPONENT + '$',
        weblate.trans.views.basic.show_component,
        name='component',
    ),
    url(
        r'^projects/' + COMPONENT + 'source/$',
        weblate.trans.views.source.show_source,
        name='show_source',
    ),
    url(
        r'^projects/' + COMPONENT + 'source/review/$',
        weblate.trans.views.source.review_source,
        name='review_source',
    ),
    url(
        r'^matrix/' + COMPONENT + '$',
        weblate.trans.views.source.matrix,
        name='matrix',
    ),
    url(
        r'^js/matrix/' + COMPONENT + '$',
        weblate.trans.views.source.matrix_load,
        name='matrix-load',
    ),
    url(
        r'^source/(?P<pk>[0-9]+)/priority/$',
        weblate.trans.views.source.edit_priority,
        name='edit_priority'
    ),
    url(
        r'^source/(?P<pk>[0-9]+)/context/$',
        weblate.trans.views.source.edit_context,
        name='edit_context'
    ),
    url(
        r'^source/(?P<pk>[0-9]+)/check_flags/$',
        weblate.trans.views.source.edit_check_flags,
        name='edit_check_flags'
    ),

    # Translation pages
    url(
        r'^projects/' + TRANSLATION + '$',
        weblate.trans.views.basic.show_translation,
        name='translation',
    ),
    url(
        r'^component-list/(?P<name>[^/]*)/$',
        weblate.trans.views.basic.show_component_list,
        name='component-list',
    ),
    url(
        r'^translate/' + TRANSLATION + '$',
        weblate.trans.views.edit.translate,
        name='translate',
    ),
    url(
        r'^zen/' + TRANSLATION + '$',
        weblate.trans.views.edit.zen,
        name='zen',
    ),
    url(
        r'^download/' + TRANSLATION + '$',
        weblate.trans.views.files.download_translation,
        name='download_translation',
    ),
    url(
        r'^upload/' + TRANSLATION + '$',
        weblate.trans.views.files.upload_translation,
        name='upload_translation',
    ),
    url(
        r'^new-unit/' + TRANSLATION + '$',
        weblate.trans.views.edit.new_unit,
        name='new-unit',
    ),
    url(
        r'^auto-translate/' + TRANSLATION + '$',
        weblate.trans.views.edit.auto_translation,
        name='auto_translation',
    ),
    url(
        r'^replace/' + PROJECT + '$',
        weblate.trans.views.search.search_replace,
        name='replace',
    ),
    url(
        r'^replace/' + COMPONENT + '$',
        weblate.trans.views.search.search_replace,
        name='replace',
    ),
    url(
        r'^replace/' + TRANSLATION + '$',
        weblate.trans.views.search.search_replace,
        name='replace',
    ),
    url(
        r'^state-change/' + PROJECT + '$',
        weblate.trans.views.search.state_change,
        name='state-change',
    ),
    url(
        r'^state-change/' + COMPONENT + '$',
        weblate.trans.views.search.state_change,
        name='state-change',
    ),
    url(
        r'^state-change/' + TRANSLATION + '$',
        weblate.trans.views.search.state_change,
        name='state-change',
    ),
    url(
        r'^credits/' + COMPONENT + '$',
        weblate.trans.views.reports.get_credits,
        name='credits',
    ),
    url(
        r'^counts/' + COMPONENT + '$',
        weblate.trans.views.reports.get_counts,
        name='counts',
    ),
    url(
        r'^new-lang/' + COMPONENT + '$',
        weblate.trans.views.basic.new_language,
        name='new-language',
    ),
    url(
        r'^addons/' + COMPONENT + '$',
        weblate.addons.views.AddonList.as_view(),
        name='addons',
    ),
    url(
        r'^addons/' + COMPONENT + '(?P<pk>[0-9]+)/$',
        weblate.addons.views.AddonDetail.as_view(),
        name='addon-detail',
    ),
    url(
        r'^access/' + PROJECT + '$',
        weblate.trans.views.acl.manage_access,
        name='manage-access',
    ),
    url(
        r'^access/' + PROJECT + 'change/$',
        weblate.trans.views.acl.change_access,
        name='change-access',
    ),
    url(
        r'^settings/' + PROJECT + '$',
        weblate.trans.views.settings.change_project,
        name='settings',
    ),
    url(
        r'^settings/' + COMPONENT + '$',
        weblate.trans.views.settings.change_component,
        name='settings',
    ),
    url(
        r'^create/project/$',
        weblate.trans.views.create.CreateProject.as_view(),
        name='create-project',
    ),
    url(
        r'^create/component/$',
        weblate.trans.views.create.CreateComponent.as_view(),
        name='create-component',
    ),
    url(
        r'^contributor-agreement/' + COMPONENT + '$',
        weblate.trans.views.agreement.agreement_confirm,
        name='contributor-agreement',
    ),
    url(
        r'^access/' + PROJECT + 'add/$',
        weblate.trans.views.acl.add_user,
        name='add-user',
    ),
    url(
        r'^access/' + PROJECT + 'remove/$',
        weblate.trans.views.acl.delete_user,
        name='delete-user',
    ),
    url(
        r'^access/' + PROJECT + 'set/$',
        weblate.trans.views.acl.set_groups,
        name='set-groups',
    ),

    # Monthly activity
    url(
        r'^activity/month/$',
        weblate.trans.views.charts.monthly_activity,
        name='monthly_activity',
    ),
    url(
        r'^activity/month/' + PROJECT + '$',

weblate/api/models.py
# -*- coding: utf-8 -*-
#
# Copyright © 2012 - 2019 Michal Čihař <michal@cihar.com>
#
# This file is part of Weblate <https://weblate.org/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

weblate/templates/accounts/confirm.html
{% extends "base.html" %}
{% load i18n %}
{% load translations %}
{% load crispy_forms_tags %}

{% block breadcrumbs %}
<li><a href="{% url 'profile' %}">{% trans "Your profile" %}</a></li>
{% endblock %}

{% block content %}

<form method="post" action="{% url 'confirm' %}">
<div class="panel panel-primary">
  <div class="panel-heading"><h4 class="panel-title">{% trans "Confirm new association" %}</h4></div>
  <div class="panel-body">
  <p>
  {% blocktrans %}After confirming this, you will be able to authenticate to Weblate using {{ backend_verbose }} ({{ uid }}).{% endblocktrans %}
  </p>
{{ confirm_form|crispy }}
{% csrf_token %}
</div>
<div class="panel-footer">
<button type="submit" class="btn btn-success">{% trans "Confirm new association" %}</button>
</div>
</div>
</form>

{% endblock %}

weblate/templates/accounts/contact.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block breadcrumbs %}
<li><a href="{% url 'contact' %}">{% trans "Contact" %}</a></li>
{% endblock %}

{% block content %}

<div class="alert alert-info">
    {% blocktrans %}You can contact maintainers of this server here.{% endblocktrans %}
    {% blocktrans %}If you are looking for support for Weblate or want to file bug reports check its website at {{ weblate_link }}.{% endblocktrans %}
</div>

<div class="row">

<div class="col-lg-6 col-lg-offset-3">
<form method="post" action="{% url 'contact' %}">
<div class="panel panel-primary">
  <div class="panel-heading"><h4 class="panel-title">{% trans "Contact" %}</h4></div>
  <div class="panel-body">
{% csrf_token %}
{{ form|crispy }}
{% if captcha_form %}
{{ captcha_form|crispy }}
{% endif %}
</div>
<div class="panel-footer">
<input type="submit" value="{% trans "Send" %}" class="btn btn-default" />
</div>
</div>
</form>

</div>
</div>

{% endblock %}

weblate/templates/accounts/email-sent.html
{% extends "base.html" %}
{% load i18n %}

{% block breadcrumbs %}
<li><a href="{% url 'register' %}">{% trans "Registration" %}</a></li>
<li><a>{{ title }}</a></li>
{% endblock %}

{% block content %}

<div class="panel panel-primary">
  <div class="panel-heading"><h4 class="panel-title">
{% if is_reset %}
{% trans "Password reset almost complete" %}
{% elif is_remove %}
{% trans "Account removal almost complete" %}
{% else %}
{% trans "Registration almost complete" %}
{% endif %}
</h4></div>
  <div class="panel-body">

{% if is_reset %}
<p>{% blocktrans %}Shortly you should receive an email containing a confirmation link. Click it to reset your password.{% endblocktrans %}</p>
{% elif is_remove %}
<p>{% blocktrans %}Shortly you should receive an email containing a confirmation link. Click it to remove your account.{% endblocktrans %}</p>
{% else %}
<p>{% blocktrans %}Thank you for registering. Click the confirmation link you receive by email to complete the registration.{% endblocktrans %}</p>
{% endif %}

<p>{% blocktrans %}If the confirmation link expires before you get to use it, register again.{% endblocktrans %}</p>

<p>
{% url 'contact' as contact_url %}
{% blocktrans %}If you don't receive it shortly, please check your spam folder or retry the registration. Should the problem persist, please contact us.{% endblocktrans %}
</p>

<p><a href="{{ contact_url }}?t=reg" class="btn btn-default">{% trans "Report an issue with registration" %}</a></p>

</div>
</div>

{% endblock %}

weblate/templates/accounts/email.html
{% extends "base.html" %}
{% load i18n %}
{% load translations %}
{% load crispy_forms_tags %}

{% block content %}


{% if form.errors %}
{% trans "Please fix errors in the registration form." as msg %}
{% show_message "error" msg %}
{% endif %}

<form action="{% url 'email_login' %}" method="post" accept-charset="utf-8">

<div class="panel panel-primary">
  <div class="panel-heading"><h4 class="panel-title">{% trans "Register email" %}</h4></div>
  <div class="panel-body">

{% csrf_token %}
{{ form|crispy }}
{% if captcha_form %}
{{ captcha_form|crispy }}
{% endif %}
<p>
{% trans "By registering you agree to use your name and email in the commits and provide your contribution under license defined by each translated project." %}
</p>
</div>
<div class="panel-footer">
<input type="submit" value="{% trans 'Register' %}" class="btn btn-default" />
</div>
</div>
</form>

{% endblock %}

weblate/templates/accounts/login.html
{% extends "base.html" %}
{% load i18n %}
{% load translations %}
{% load authnames %}
{% load crispy_forms_tags %}

{% block breadcrumbs %}
<li><a href="{% url 'login' %}">{% trans "Log in" %}</a></li>
{% endblock %}

{% block content %}

{% if form.errors %}
{% trans "This username/password combination was not found. Please try again." as msg %}
{% show_message "error" msg %}
{% endif %}

{% if demo_server %}
<div class="alert alert-info">
<p>
{% trans "To test Weblate on this demo server, you can log in as the following users:" %}
</p>
<table class="table table-condensed">
<thead>
<tr>
<th>{% trans "Username" %}</th>
<th>{% trans "Password" %}</th>
<th>{% trans "Description" %}</th>
</tr>
</thead>
<tbody>
{% for name, password, description in demo_users %}
<tr>
<td><code>{{ name }}</code></td>
<td><code>{{ password }}</code></td>
<td>{{ description }}</td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
{% endif %}

<div class="row">

<div class="col-lg-6">

<form method="post" action="{% url 'login' %}">
<div class="panel panel-primary">
  <div class="panel-heading"><h4 class="panel-title">{% trans "Password login" %}</h4></div>
  <div class="panel-body">

{% csrf_token %}
{{ form|crispy }}
<p class="helptext">
{% if can_reset %}
{% url 'password_reset' as reset_url %}
{% trans "Forgot your password?" %}
<a href="{{ reset_url }}">{% trans "You can reset it." %}</a>
{% endif %}
</p>

<input type="hidden" name="next" value="{{ next }}" />

</div>
<div class="panel-footer">
<input type="submit" value="{% trans "Login" %}" class="btn btn-default" />
</div>
</div>
</form>

</div>

<div class="col-lg-6">

{% if login_backends %}

<div class="panel panel-primary">
  <div class="panel-heading"><h4 class="panel-title">{% trans "Third party login" %}</h4></div>
  <div class="panel-body">

{% for name in login_backends %}
  <a class="btn btn-link link-post" href="{% url 'social:begin' name %}{% if next %}?next={{ next }}{% endif %}">{% auth_name name %}</a>
{% endfor %}
</div>
</div>

{% endif %}

{% if registration_open %}
<div class="panel panel-primary">
  <div class="panel-heading"><h4 class="panel-title">{% trans "Registration" %}</h4></div>
  <div class="panel-body">

<p>
{% url 'register' as register_url %}
{% trans "Do not have an account yet?" %}
<a href="{{ register_url }}">{% trans "You can register." %}</a>
</p>

</div>
</div>
{% endif %}

</div>
</div>

{% endblock %}

weblate/templates/accounts/redirect.html
{% extends "base.html" %}
{% load i18n %}
{% load translations %}
{% load authnames %}
{% load crispy_forms_tags %}

{% block breadcrumbs %}
<li><a href="{% url 'login' %}">{% trans "Login" %}</a></li>
{% endblock %}

{% block content %}

{% trans "Redirecting you to the authentication provider." as msg %}
{% show_message "info" msg %}

<a class="btn btn-link link-post link-auto" href="{% url 'social:begin' backend %}{% if next %}?next={{ next }}{% endif %}">{% auth_name backend %}</a>

{% endblock %}

weblate/templates/accounts/register.html
{% extends "base.html" %}
{% load i18n %}
{% load authnames %}
{% load translations %}
{% load crispy_forms_tags %}

{% block breadcrumbs %}
<li><a href="{% url 'register' %}">{% trans "Registration" %}</a></li>
{% endblock %}

{% block content %}


{% if registration_open %}
{% if has_legal %}
<div class="alert alert-info">
{% url 'legal:terms' as legal_url %}
<a href="{{ legal_url }}">{% blocktrans %}Please read our Terms of Service prior to registration.{% endblocktrans %}</a>
</div>
{% else %}
{% trans "By registering you agree to use your name and email in version control system commits and provide your contribution under license defined by each translated project." as msg %}
{% show_message "info" msg %}
{% endif %}

{% if form.errors %}
{% trans "Please fix errors in the registration form." as msg%}
{% show_message "error" msg %}
{% endif %}
<div class="row">

{% if registration_email %}

<div class="col-lg-6">
<form action="{% url 'register' %}" method="post" accept-charset="utf-8">

<div class="panel panel-primary">
  <div class="panel-heading"><h4 class="panel-title">{% trans "Register using email" %}</h4></div>
  <div class="panel-body">

{% csrf_token %}
{{ form|crispy }}
{% if captcha_form %}
{{ captcha_form|crispy }}
{% endif %}
</div>
<div class="panel-footer">
<input type="submit" value="{% trans 'Register' %}" class="btn btn-default" />
</div>
</div>
</form>
</div>

{% endif %}

{% if registration_backends %}

<div class="col-lg-6">
<div class="panel panel-primary">
  <div class="panel-heading"><h4 class="panel-title">{% trans "Third party registration" %}</h4></div>
  <div class="panel-body">

{% for name in registration_backends %}
  <a class="btn btn-link link-post" href="{% url 'social:begin' name %}">{% auth_name name %}</a>
{% endfor %}
</div>
</div>
</div>

{% endif %}

{% else %}

<p>
{% url 'contact' as contact_url %}
{% trans "Sorry, but registrations on this site are disabled." %}
<a href="{{ contact_url }}">{% trans "You can contact us for more details." %}</a>
</p>

{% endif %}

{% endblock %}